---
title: "Data Visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load packages, message=FALSE, warning=FALSE}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales)
```

```{r, load data}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv"),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"))
        return(esc)
    }
)

head(esc)
```

```{r, separate}
annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink"))
head(annual_esc)
```

```{r, plot 1}
ggplot(annual_esc, aes(x = Species, y = escapement)) + geom_col()
```

```{r, plot 2}
ggplot(annual_esc, aes(x = Species, y = escapement, fill = "blue")) + geom_col()
```

```{r, plot 3}
ggplot(annual_esc, aes(x = Species, y = escapement)) + geom_col(fill = "blue")
```

```{r, plot 4}
ggplot(annual_esc, aes(x = Species, y = escapement, fill = SASAP.Region)) + geom_col()
```

```{r, pipe plot}
annual_esc %>% 
  filter(SASAP.Region == "Kodiak") %>% 
ggplot(aes(x = Year, y = escapement, color = Species)) + geom_line() + geom_point()
```

## Setting ggplot themes

```{r, filter Kodiak}
kodiak_esc <- annual_esc %>% 
  filter(SASAP.Region == "Kodiak")
```

```{r, plot Kodiak}
ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point() +
    ylab("Escapement") +
    ggtitle("Kodiak Salmon Escapement") +
    theme_bw()
```

```{r, plot diff theme}
ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point() +
    ylab("Escapement") +
    ggtitle("Kodiak Salmon Escapement") +
    theme_gray()
```

```{r, improve plot}
ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point() +
    ylab("Escapement") +
    ggtitle("Kodiak Salmon Escapement") +
    theme_bw() +
    theme(legend.position = "bottom", legend.title = element_blank())
```

```{r, legend}
my_theme <- theme_bw() + 
  theme(legend.position = "bottom", legend.title = element_blank())
```

```{r, plot custom theme}
ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + geom_line() + geom_point() + ylab("Escapement") + ggtitle("Kodiak Salmon Escapement") + my_theme
```

```{r, plot theme with angle}
ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + geom_line() + geom_point() + ylab("Escapement") + ggtitle("Kodiak Salmon Escapement") + theme_bw() + theme(legend.position="bottom", legend.title=element_blank(), axis.text.x=element_text(angle=45))
```

```{r, smart scales}
ggplot(kodiak_esc, aes(x = Year, y = escapement, color = Species)) + geom_line() + geom_point() + scale_y_continuous(labels = comma) + ylab("Escapement") + ggtitle("Kodiak Salmon Escapement") + my_theme
```

```{r, save table}
ggsave("kodiak_esc.png", width = 3, height = 3, units = "in")
```

```{r, multiplot}
ggplot(annual_esc, aes(x = Year, y = escapement, color = Species)) + geom_line() + geom_point() + scale_y_continuous(labels = comma) + facet_wrap(~SASAP.Region, scales = "free_y", ncol = 2) + ylab("Escapement") + my_theme
```

## Leaftlet

```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
datatable(locations)
```

```{r, leaflet}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~ Location)
```

```{r, leaflet wms}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```
